language: python
python:
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
 - sudo aptitude -y -q install unzip chromium-browser
 - mkdir -p ./tmp/bin 
 - cd ./tmp/bin 
 - wget http://chromium.googlecode.com/files/chromedriver_linux32_16.0.902.0.zip 
 - unzip chromedriver_linux32_16.0.902.0.zip
 - cd ../..
 - pip install django splinter pygments misaka psycopg2 simplejson --use-mirrors

before_script:
 - cd djangoproject 
 - mv frespo/env_settings.py_template frespo/env_settings.py 
 - mkdir logs
 - psql -c 'create database frespo;' -U postgres
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
# command to run tests, e.g. python setup.py test
script:  export PATH=../tmp/bin:$PATH; code=$(./manage.py test core); cat logs/frespo.log; exit $code
