language: python
python:
  - "2.6"
install: 
# - sudo aptitude -y -q install unzip chromium-browser
 # - python debugtravis.py
 - sudo apt-get update -y
 - sudo apt-get install -y unzip chromium-browser
 - sudo chmod 1777 /dev/shm  # see https://github.com/travis-ci/travis-ci/issues/938
 - mkdir -p ./tmp/bin
 - cd ./tmp/bin
 #- wget http://chromedriver.googlecode.com/files/chromedriver_linux64_26.0.1383.0.zip
 - wget http://chromedriver.googlecode.com/files/experimental_chromedriver2_linux64_0.2.zip
 - unzip experimental_chromedriver2_linux64_0.2.zip
 - cd ../..
 - pip install -r requirements.txt --use-mirrors

before_script:
 - cd djangoproject 
 - mv frespo/env_settings.py_template frespo/env_settings.py 
 - psql -c 'create database frespo;' -U postgres
 - "export DISPLAY=:99.0"
 - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/cucumber_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
 - export PATH=../tmp/bin:$PATH
# - chromium-browser
script: ./coverage.sh
#script: echo ./coverage.sh

after_script: ./upload_travis_reports.sh

env:
  global:
     - secure: "QB/rA0j6jJoki/BD/m+KxyCniqOb1pEC93hOrotblbpptjgrgjKeEPPQBff1\n1gvHT873Mf6d52OHhoeNMNxAumPpJGao2Mpe//qpXqkzPvwroOrfpiTkDYrH\n56sMB1ntG3h84jWCgrSlzZtZFaKhHPify1p42rr5GMQ58eKbs3w="
     - secure: "OllLDXDFG0OaR0TpKwW5yKKjZf1CnFXw59NCPDQiZFsglPugh6+Tekil8Vhl\n29CX7rQwtDtNgpglrd+rZFI9xNxWZSHr0PDEttX1flZhGl0zyTDbeO+hzOag\nPtRg8TS0EaVjqwKRzsDuXJnftC1SJYaayyIcmsKd/jPfZSxqeOg="
     - secure: "Z0bSC5scOvcWEVIOh0hAuJTbxPuXtUyjO9+F7TVgf73pI3J/+ZGDq8+jssmk\nC8LKp2hRON1Tzw5ScV+XHVqexiHPfWHey4A0MQ3nqZmroU63Sc+OGON9T1VO\n9Jx92b5HXDX7ivlzRDM/yT65cfWJdSReaqPhv4HcA5ICyIjm/k8="
     - secure: "Q4aoOTtCpg3+XFitdXP5zwl5GTQmNg25U5EwpjjtivCS34IuKfTqlForh1MX\nkMDL8sgqAoZeIF0udMQpYY7YZK39QTbVLGJnrqf9OBbm+M95Lmnmq4fbv7jj\nRqRSd6pw8V00jqvyRcNJte2SH4yaJUcKL75YQWOEFGTTonz+4rE="
     - secure: "IRqh5vdQgOuCCZJXHuPxMDVFh8plDRMymBPUWWnsoM5p9J6j+cTPMmUgnX45\nR5emNRaI2GC0iHl3enjPTddGovQYDfDsWuygDkDuHCzjj+zCRG5vVrAPnbNH\nH3yv4GptN5w/EmALSCpf2670ua/xm+pggQ1aPVgYW8IumLIF6IY="
     - secure: "H5f3olsV/WYjt9Xyls2bT/a7IFQr4wrRb0sdXSIhojY97GjDDFSOetf03qOE\njT7HkKA8krFnVQ1oyT2TcHMwQ+SD32oSZR9jsWG9zumQyronv7iAYMv8p6rG\n/sRvs6YFwL7mVFvMoX1o9tYsrAJYEKKvVx+u5HmETZafn3XqXhs="
     - secure: "XlcLEL+sr4Urtt7SixEeLNPPFAehwjGdXvQvxcYdn32s8+5OpImO/YD1GMhi\nAdgO3PTIYzMETABDAd1NZZ7RaTOkgFVgn9ZFVbsJHItDG9TtRF1Vzbjh/x+2\njxR4LtrHy+eNrNgv+5VcvhCJVy3yTVZMwIFsVi8jhme73bZVSSY="
     - secure: "bLkkCvyv/L6N3oACCRKhz1ZStcnqs1PqmLQ7Lja43v8DkLWusTmWgwI6MKq2\nzMKeiuDmmvmDMKhdF0M6XrhZaDYr1nZLslHLbO5t3euGtruXd6/UjdNVaa4o\nBagTOi3LxJ1LdfeYLpr7fMJx59eooPiNDZBJJp0SzLae+ysJw/o="
     - secure: "ViyeTDLP593rYXUdsnxdYm17gZ1x2/ku0OKnfTm48FVzo+QePQHAymgt6PCe\nDuJioqwqNJNGZOyVparurZUunvdbe6eedasuXIJahH6WCFCNWg5vf+44TZ6D\nCNot887W56KDr87F5LmA6wUbhXJulh5IwWzFge3Tvg+hmpLFVdI="
     - secure: "A1GJA6OT+c51nnTLWr/6tk9VcwV8Qzrk4bNaMxT7/VmT3nWMWN1hfAAyWbTW\nuTPUgcNtz+X2vCP6u2x7TeBuXlkATke6sSZzlDO1x39jhWo9fqu7Y5xkRmd4\nvB+w+Bus331uwKGKwpnAHa8whDS4ezvZrJla48W0gbbjGbZmErA="
     - secure: "D6f0IFVD+dF0ge/fd5D8fq2zLV/xUls78VPKaoPhbJKqfmX7fMQ+KfwlhRxe\nqvzFxzHD4u8Uj60Emm9Ak/uxjZBB0taNS7fKU4GA8KB6J8DroFWHOOZYboA/\nNBX8d4cod4NG8gSTyI72xFfGzZ87RZu2rLSGnAb1JkXwEPwV2zQ="
     - secure: "EaDi4cXUBf3ln1R8XkgKweWqheNHxfBsDqYbIQfacxwvqRNBPHh/EBxd0V0s\nZxOUC6EowHpMbuV1d8flUcUTfWZDcT7FupOERTtGO3PxriNfZxJBLzoKDtnK\n1VzdQ2gcnYOPgkvrEf9+PRIyW5aiu+50mz4E0wX2Nr8eCouwTms="
     - secure: "Di+doOcFLXEh4SWQKztnMFs/IyCN01176J0lwLOq4pLm3g1uYinGEWVhQirw\n8N4v6cdSUk0ZyUZ75JUEnAJA41EgQE2nTLYBX5HKmlSkMjNyG7u2cgpaKaT6\nO8nDoxzegjvdaSBzzK15mupIccHmSqEXO/Glsn1/I7arXOiL32c="
     - secure: "C2KMjrTqByJYWG8VDmiNlv7aB2e6GPzI1ZAfG406XGsmbA8hkmTcyOnuNSby\nr6sAhEUUd3NsFQRl0lO+2iRmm23paiL2okUwZOT8E3R5O+iTusNu8HZxVO+U\nhgqZhn4YDLQMvK1I5ole7JBPlIZ6sbYH7+0YFmDSJ3aH2qT+40w="
     - secure: "KsjvqZIk6KuB7lFrZErRuIZzp6P+T7NFQ6n4qcMic+B7P/9O6TUoAZy4uYYD\ngbLf9LgL0QSYfgnYzLiUqH7HnWxQXpPoYCtn5Nu0+y1/oKPf7YzDnrrDZQf+\ntFsopUeNzdJBiehXhpf5QKRXGZ5+RAr2zwfzHxU5jzVbGxhEEdc="
     - secure: "JPOJID2cR9Czd57w6eKg5EaNhKh3e1Z0TpC+oNoaJIRWur1sx89VKersOKwl\n9gvvxpiiWqubdTwn/tAWLr3QICC+dgvpJeaFt2AaKTnHSESLptkFtE+HvUrS\nszGJ9Ix18b9sJsKhzISlugQTxsQ7JQj8R3Zr1cU1RAp3bC8jldA="
     - secure: "BiPz8/38TUKXj2CJo96vDwzyPA1meVSrbSZWbTMDTT9pKXfO4pkL4zxULRj/\nON+ukWtFPdIWOc1kwjk+TK5kIwGVQygA6VKzUa2hUGxlG1c5lom+CFjiIaZC\n4KYTrTuYPAwCmtyjzSk2SVWDkFRLteiMKxsq6MaUny6oRIy6ueQ="
     - secure: "QTFBYfC+xeRtntzLArbgj0G7rw4qrmJOVg3tCnaLchoxXoHgEQI7hnzh0A2s\nUcBR8AWse4pMXdcF/my4+YnFRwWJotQpDefiOdTOvswXOtAi9z6akTvsfcET\nIHGA94EEqyw3Y9JlCi3++Ft7nsmByt/3Q+vSgPYEgTApQhS/xg8="
     - secure: "MNr1V/ixDg+Su6BfGoyBMKqZ/NWFVs3b/nNHayipKZ7ia1q/Efamjf2Bo3fa\nGT327/2n6XIgQiWmdMCUUC5p9W105NtzN7jzP9QKoeZG+vJwjLsdQ2buGOc0\npoC1rHsFvConYrwtNpk48q2y0k3SHPE3yHbn50LAaZazRKEfMCI="
     - secure: "IjU8kfDPWRUnsgQYiILSN/a4eZTFJLVQQUpxQGteviae3iqq1YY4Hj44Hyw9\nNW2crZZUfG6QQhst3uW/jFktf8wVdARPUe3+OpPuaRB7HwBjbLJWJnTV1pCy\n+mXLQ38/59Aejyd8IIbukwZpIJLHkdWaV6cTQzonrn1ssMub36w="
     - secure: "DW+K/M37KZlu5OT25iqZHIrRA555W6dyYH3vHOsdqLfeIcG5l8fG9XvL43uf\nUlp1xgGGo3K2dXtLHh9jKXSxfct5QD86vzEB7Svu1yl/1UQxo5UcX60ZbBJ2\nV6tCuTc6G5FHZ6cJJiWeuyRMHUe20xo4IAPnnU/usDbGKQYLiDc="
     - secure: "a3DEKkkOvAMukencw31blnbrpp7j3Vukl4GK498MU3sL0StJQhxHeQAnUrza\n2tSiKTxEeuGGVWpDBbDJxul/RqFgN0G34xQdwJ8B9M2gmb1kDdgph/LC7yR+\nQnwJX69+GjECy3apjmHrwVRRZVHNBJ1tXsqRep34VcyC2v2iM8A="
     - secure: "VNUz4qLmst/nwc8/qrsW+F3XAjFAXNlEwxamv79vAHOuZfzs5Zea52ECo5X3\ntkL26cIc5D5yJ4q3VWrsBBiGmuR7nuOcUow/r1AJB1CUXIkOeE2X8E9+Iiuu\nRa8PC6jZjJ5UTraoDwTYKlQaRpiihpraE59uEm5feOJ/PMYQsOY="
     - secure: "DI+U707aOgstKMbNubfX9mqGuxgeaO4rzgCdobaQ/nDXfBqVOPt4QA+wbWSy\naeDoCDolnjJKS9Gys6ClvEfWGopsELf6kT7XeCNa26Po5QrO6KkCsmttj/Ne\ns8tiKQbDITwAwOIuGkpj0AI+yL5zZC6t+Ae+cgcyeSdvHCk6aZc="
     - secure: "OnZV2YG/XAixuUtpaI8qTLy1vBPTj4g5l5QzaD5yIikoa5SXuXEkFgSuIbM1\nnfEzzPsUVLwH4spNIxLItxKAtVfgNmtpye8wNbHjebpr5R1g2GynxUiIWDjQ\nwSUDsnMV2i/M+MkghyBnuxiHLY79jIgObzo9ueALjjFQQM1NWO4="
     - secure: "TkQO7D/8A7/cwnnKDBO8kZmRVl4o2w8d7C3zruT+blvuthwwsWYlRMyvT4+4\nmSVOhtoqsmVT7agU6dnO5NAS7J99wvAoJCQ5Cy/k49ANaWE8dnzffEuYlKc7\nCxBIl+s5ww+5btoXXTqTcyBoQfUCXV8KTs8RlS9QVaFIcC0Q3H0="
     - secure: "BSTQn9+Fb8JEFOhdXz4Y4CbESeuj4URjHqXmZBUKOI1QsVmCOuE+jyq/Ec9b\nR7Tj6zqyprOHivh18ghCnIIDT4KXwh12ispv+BwQg30wHLbTiCAbbL6wrWvA\n67gJad7BThsmZ+ovBsbjJputw7GIFKk5yBS1L5oPNDxhItlAd9E="
     - secure: "Vy/8aVGzgq0NwhFmk4fk6fuAB2GHzwQGl9IXBLRITuqUWI188vtOgi7Hcyw/\nKVRRnhycb6PmUz5KTPvQE4vApI1RqlsiUVXfeRnM8Nbtc6bKFZXjD0AYU9wz\niId9wQ0+BhJYPsMyRZXnG+RLdX6xWpSQQy0rOyGp5fbxTnNYDvw="
     - secure: "SjW86R6QbyL5SNcDkD6S4EU++8yyE6Bii34XxPBp7Q8UOa2PGP0yy5jxIONU\nDQRgbCqTPE0xz9pqiVg13GBBZqq3HeO0MSKm8CKDyU7S+VdImxtXjptthkox\nqGoy3oC3eaLPzJIPs10h4DP5FuEZj1jgxyyjuL9v2l20SWUfzt0="
