language: python
python:
  - "2.6"
install: 
# - sudo aptitude -y -q install unzip chromium-browser
 # - python debugtravis.py
 - sudo apt-get update -y
 - sudo apt-get install -y unzip chromium-browser
 - sudo chmod 1777 /dev/shm  # see https://github.com/travis-ci/travis-ci/issues/938
 - mkdir -p ./tmp/bin
 - cd ./tmp/bin
 #- wget http://chromedriver.googlecode.com/files/chromedriver_linux64_26.0.1383.0.zip
 - wget http://chromedriver.googlecode.com/files/experimental_chromedriver2_linux64_0.2.zip
 - unzip experimental_chromedriver2_linux64_0.2.zip
 - cd ../..
 - pip install -r requirements.txt --use-mirrors

before_script:
 - cd djangoproject 
 - mv frespo/env_settings.py_template frespo/env_settings.py 
 - psql -c 'create database frespo;' -U postgres
 - "export DISPLAY=:99.0"
 - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/cucumber_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
 - export PATH=../tmp/bin:$PATH
# - chromium-browser
script: ./coverage.sh
#script: echo ./coverage.sh

after_script: ./upload_travis_reports.sh

env:
  global:
    - secure: "SbebTaplVADIzvdFa/4gFWtTCUwwuMSJPlD3iNwizd0zqlfNc5aWM/jIW76Q\nGFhDSWu6Ol7f4T9HmMQjJE2bUSRl4IE+BfI9AuEfFjJt3AiPI5cdaVgO2jLy\njLUVTeqYe5KQrFuiOpAjG0rmGQUvecgbugt4P3TsS0FKG5Yqnko="
    - secure: "bhIX019sgjn+PIcGOWc4YcaL0lohZx2kV96kLsBF9q3YyOusdFddGph1CXY2\nFFdLOlCd7XZVR9v6+nTvbZR8J7JZmEsJaO5/H4idPcZ2ccJDaixISy8r0G8b\nIQAM97fUzGkldsATeTchiZqqZ1DXreW8Dme+weOln1YJIZjvV78="
    - secure: "F+tC8ckD3107LUUWzk3Xbs8XZxxBYDz5IzjYLznBvwaVAL727hWNMfpWWpFG\ndZUHYRZ5x7Ic5QsjL7Oyux5mIapkR9g5pefAMSFaXJXs8MjauXUoc0odtmO4\nzUMTa1kB/pc4JYuGNhMc2qb94vmJ8Cqb0g7mM7XUtaCYHHUHw5Y="
    - secure: "ODzRjlCsP9EOzXJ9xLitFObB9lX1TOzqdC3gFWw53rP9qsGoLOWsY8SkzSrz\n+rt5UhQLFUO5pGN+7it0u2n0Xvv1UCxEnPEhaAYvxJya/T7jeklZwTaJN4Xc\nMgMDBnCIvvNOoylGwunpI0oHky56yXWEbDZgxOF1ifcVadiks40="
    - secure: "VRRCjlzq67m4WclWmR/qKF4K0FDJRQWXLelpQQiFrX+ui2dV+7AE0TBM3fmi\nnS4LpV8Bjdtc18BDF7kruZt9nLdaSnUM32qrNQqt4+WNM9s0lZJXmPDnHBvk\n0TQqW+U1x4OqRvdjPk5cqVtlZPp4MMDUSFHMSowlEXwF7wtHpao="
    - secure: "VgF6pr85M8XwEHLjSqVCkTg5CBY6aXvlV2+pr6QPmSl+DmlkS7kX0XZ5VS1/\nlu1yW8fzNRKrA8rql0WV2PJRr+bmpP+gbc83BnXi3GpPdQX0i6zMvfA4eqaJ\nA95UIWCVYrVmeqz0HJl21WJD7GplfX1y3+3x7EwxDE5MVX2iMI4="
    - secure: "f786o8CBqM0DP+76fUbnGhPFvYDoHhVFEK0r5knUJYDxkhtgh/114P1lBfqr\n2R4vkVJa6creWM+Ydm76WFO+RdTkd36lC2/Ilwdx+U4OAr2CKcRFd+/LZKiZ\nkgj2/8w8BhD77mQHr/Dumgi09TJkgsP/DgJJaSYGByBzNBDUWe0="
    - secure: "XHpDN+gnZ96+/GpzJ6/CVRevmRFh/2RLQrLf988IFb2PlRGCdbmA3487tGqx\nbKkXQRgfm9zDh6KIcAMvwP7/awoHrKwyItMnfD3Maod7Dg3+doBv4e3Y78SU\nDtwexl9Btr9jtAgN7s4agq5uAE8YKLzSfiZTONxnOSng1Y43wC8="
    - secure: "I/C+aK0zyI+wFApA7pTPkS4pU+iUUfpFIiMNuFCRdPNX28YfpsbOkT8oEL4Q\nCHqU4up4ax3EUXtqRcR1XWlfYpmXrwl4rLh/mC3ipV4CqzAoG7CH3W5uxb6p\nP7giDS2m8Vbq6n0zN2friVZ+FE2VeS4EboYaplqbgQUIIVEjP9E="
    - secure: "UAFJVgZzYTSNqRao6i/sfcoN8ndaEsosBBKzJpFxvER0eg5yk4YUD5mchIET\nBnHlBpDCc6KWSBvckHmsBNzRNLOuPEY5gUChFZSgru0Unb8qHvlL2aALnZZF\nLmQZEAlDYzKeqAG3+XMm9woDnOKweamlQEeWlspygQjhjZ75VxM="
    - secure: "TwvXOKQfs8FSdWC0pm+aKja30iRLdAy3yxAAW5uKvZFnBno3YgxZSdx/OTtR\nMPA5sb1vel5occdjc3+928Oz7PoSNZhQ8vo3rm105VWi0IMgQdzI0q8FbtYe\npUZ2Iry78vt3IfaLkyIJwzKJ/I0bTN62FHWanxBzKylqdl244/g="
    - secure: "cxJ9kprTgt+G3aaBWRLbszbaFp8lR0Sc6uau6snsyjtVmkh2ngZwITBz5Z88\nzdKeZVIT10OVqeLwIp63Isb7PqckQ+8yj/VZViU1+No059Csp1KoxVEMDyxE\nbtaM3ryqP/HWFnQxfwy8fyv58RC6Ud6QLXC4tElHmh98/GZfUWU="
    - secure: "Daxg49K7wilTihZ3FdRFRNJ+EXeS2FC79IB/7y0IcN6JRbF2+ouHes1l5X7T\nbJeA28Wo/CqjDH9X2QN6IFmjHvBZNYRIrOjLx2xfXLUD6V/cKiOvBk4tm90i\n3ciVKaIerYYa8qUVH3lw5jtHAn3KeKrL30x6tUSUHOkSi0r6zUE="
    - secure: "PwA9aOv1b/DZ749HXV1NFtq6B05k73ha/TgCBnz67JApUh3wbcOUhX8PIKZQ\nbcB2BkOySmEFBK0kt79+YGp2uHWcDIun4cSgSXZMy9VSMKhg4JLXGa+KdAwX\nVtRZ9UypDyuObxlG6iPiD1xnWFZWeOzaZQgOvG5UR/QZqz5Vlmw="
    - secure: "PKNgI5tGdJtHDqEslXmr88VGqtDDyXPMi4QIdRiE0T2PbAA+48qTLgLBVNjr\nVxKf4s5AJMY7sucB+Q4CeF/7dQGwYt7wAkuLgd6zzyhJX0mh9zM4OmFJVY/m\nkq7oXtj6QUleXcnrW7A6vNrXZ9cnjWQCHTLGJIM58MDZyKyhmRE="
    - secure: "bs+RO6KxcOv5nUQp3KuCiNO/IhhTlOEsE7GeXCCLmlGBoZHUtY5VrCGPihpT\nRuz6rbyCkC3sBcrtA8roSvZ3SvnxA/m1T3udImSBUP7ZuQZmDQvPNIG0ocFg\ny1AVGmDjbXSOBjhJH5XB4Fm1izzVTG+jmmKMXc5ulCJn+dGqpqU="
    - secure: "LF7vntvWzscd1G6C8c0Ycxx7R7ULIdzMIBMxS4yHqFxbG1EnG9ZCB8o1jl3d\nV1hFTVi0ttWwN8XJctTxnrSklutePfi7759roQERZX/+Y/bFchkhowW2ZXab\naDV+0EWwEvdVTjmYpMXclJmPBPHOJUyOcfbUTn1E/ON5nYzonMo="
    - secure: "ciNv2gDO2/ixeWGQOX2aDOOoKtUIBthhEwUkbb98Q0dDbt1VTkUpCcsNN7Nm\nvfqGvmFk0Pwyj01pZuie1+8Yb6GxDGt5YmE/ymvK0WngWF4kY2dtg4VwUnTz\nE+bdo34bIfM0x/B//Lx/PRV1EAraLWcmDbvDqxkJPFfbprPvlTY="
    - secure: "Emew4y3veul0Q/BYR5hKZLVSUdyl3za3vAQaUoBPvj5pquLaFqOtuO87xNut\n0kiqSocuwOxe6WikBes7asTts7E/WT2gExCXoyut7c85gSjsLCeM1JpNQeqB\nqaxuFRd9612BEonnS85I/KW7YmdgjlgtGeEgLLxitVymqwEaVsI="
    - secure: "JrdaFnIkNZVSpmzJXGGZketNy0alXalcZ8zxHHijwjq7zEykRKO2P3Bt5/uy\nL8SRbKakYpwUwfKpNGJEDrsqab3oTD2c2Tn4pWTlRkGXnqNrauj1UoQh6MVl\naOlCkVA608FtVXDk6v21CLycWAdVkUYvE8AEP3Ki7c0CY+sm9Hs="
    - secure: "IcTYkPzM8AuLk4zKZgO15nS3nuKd5N3Vt9DagdYSV8FDAB9bgvUdf+cBNWGC\nvd4gjbL2L091fM75UQwjQDNax5Y0oZXhl3CDvJdRJyvJbZ9il4wWIm5gefaC\nsjEJxz/n+9CA7lYxePLzdYKz6zBENkUuPg9x7NZoFTmWEj5tgnQ="
    - secure: "Nl8zd3ERDKLLWZJ4V/3+dySukjEQRLHHYIIQAu/g2Xq/AsWUDNtCCC4jSBTx\n8S6TAQMKxojA8295d4Ofwd0o9cjle/mHGX8wn+CYD8Dh/6PXssnaOWdO1sMx\n0JUdg4SiAoZ1bkEEwB5IbtzFhtVLhG67bpVC3pvyP2UIfC3EVVY="
    - secure: "Tz075ro++bGoQlyLBWSITzaAcU+Zdrb0dZqptjjUfiu+bd5Ex0VePvROqmXx\nEJXX8JGW+uSDfXQZzv9B+2Xbg88QYZgh68DUUYsixQvJ/Vzm7UfC7Wd9/S2V\nwX0kISukpBXddG/JeKJiamwAM2K3cTHcvpG41EZOiSnjj+p5/DM="
    - secure: "fQIY2bRxuSpv50EKntTiCpKXQzRSomw32NuRtbAFjxqrEvItvtkzFIo6j/Jg\ny0PMlJsEWOnoWLJx3Z7KzJYQ233PNl9MEyM1Py3HUm43cgo7LJCrGq2htxwa\nI+3Zkl1hDwZiTauudi81Ct3HVkM4zPWq0oZBxrap6RkLd7MXmVU="
    - secure: "I7mJYxZrVRAaVVw+5CTscVIPSgqyGKtDiVc12hheNa8uo6yNNkLbk6naEBxW\nfdQetvGn4oegYJLKSv2sHmgCz5ugtMa47kOtKoxSKLHWeIw7Phz8K9d8Kwp+\nd8gywBYOGnnBwCxvQawJTpBBNuIQvIZ8fKfoiXT7HrCxd6PXzDw="
    - secure: "RYgPRBVy6VsXBvbl5VMFUVGdR7/YTcJm5UaOmPmUeWxZaItUWpKxL8C3HMH4\nt2JS83KPdN46KwY5uqr3ZOTkgMMQ4ZkM9to7eoRULw19d/KaJDloKsjbfry7\nP3Gv0VsIVAenYxiymCjTP8q8tzG/clo6dLdF2l7ia+7BrpM+ib4="
    - secure: "ExeZ5MugPSHlHG9RxyGr2xba30iFrFgNy144XUIQElCcy/85nUgN9Y62R3VN\nsOct6e7OC8Y890zOspiYd4yzffMWQcZxoK92sxiucv6KfiPe2+6TczcneArM\nwxODNEsfLgdwYRKOiNFE7TQ+oCM95i4yNLqznEKBCIYVye89510="
    - secure: "IrZXquOTnb6XotScsjyiX2nQgO+pFTOVFn4axCScYiBBVxcWu8yiZzWzUIXE\nFNZ+X14kG2o56dg58yA9ia9n+U6zCpGVoMUmSseX0t8C1Cyls9gCRCPYNtXm\n2+sj4bb8VDYQAU0xSolKGCMfi2B+7nspKvugebHvdpz7knIu/r4="
    - secure: "e04+p9OgUGDF0+xFaDnqWdqsHJD1Z3nmX3tnnhfeaJi/oFbZyph78EiybQVQ\nOImSf1VVvPomtNczSrxZ36LfDcVSzZoZLjDJoEHo5VZ0IM7aUfAR8I0/Xc4y\n6JXf0wlerW7BQdxMAQ92jZgkWLL1rcMbB21FFKo94P9hYa4uq9E="
