language: python
python:
  - "2.6"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install django splinter pygments misaka psycopg2 --use-mirrors

before_script
 - cd djangoproject 
 - mv frespo/env_settings.py_template frespo/env_settings.py 
 - mkdir logs
 - psql -c 'create database frespo;' -U postgres
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
# command to run tests, e.g. python setup.py test
script:  ./manage.py test core